FROM quay.io/keycloak/keycloak:26.4
COPY custom-theme /opt/keycloak/themes/custom-theme
COPY keycloak/villagevandals-realm.json /opt/keycloak/data/import/villagevandals-realm.json
ENTRYPOINT ["/opt/keycloak/bin/kc.sh"]
CMD ["start-dev", "--import-realm"]