spring.application.name=VillageVandals

server.port=8081

spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:vandals}
spring.datasource.username=${DB_USER:user}
spring.datasource.password=${DB_PASSWORD:password}

spring.liquibase.change-log=classpath:/db/changelog/changelog-master.yaml
spring.liquibase.clear-checksums=true

spring.docker.compose.lifecycle-management=start_only

jwt.secret=${SECRET}

keycloak.base-url=${KEYCLOAK_BASE_URL:http://localhost:8080}
keycloak.client-id=${KEYCLOAK_CLIENT_ID}
keycloak.client-secret=${KEYCLOAK_CLIENT_SECRET}
app.secure-cookie=${APP_SECURE_COOKIE:false}

logging.level.com.villagevandals.vandals=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE